# Generated by Django 3.2.15 on 2022-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_familiar_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
